<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo('charset'); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- GTAG --><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="format-detection" content="telephone=no"><meta name="description" content="Astro開発環境のサンプルページです。"><meta property="og:type" content="website"><meta property="og:locale" content="ja_JP"><meta property="og:site_name" content="Astroサンプルサイト"><meta property="og:title" content="サンプルページ"><meta property="og:description" content="Astro開発環境のサンプルページです。"><meta property="og:url" content="https://www.example.com"><meta property="og:image" content="https://www.example.com/_assets/img/ogimg.jpg"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="サンプルページ"><meta name="twitter:description" content="Astro開発環境のサンプルページです。"><meta name="twitter:image" content="https://www.example.com/_assets/img/ogimg.jpg"><link rel="icon" href="/favicon.ico" sizes="32x32"><link rel="canonical" href="https://www.example.com"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="preload" href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&#38;display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'"><noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&#38;display=swap"></noscript><script type="application/ld+json">[{"@context":"https://schema.org","@type":"Organization","url":"https://www.example.com","logo":"https://www.example.com/_assets/img/logo.svg"},{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"サンプルページ"}]}]</script>
<?php wp_head(); ?>
</head>
<body class="page-top">
 <noscript> <p>
このページは JavaScript を使用しています。<br>お使いのブラウザーは
    JavaScript が無効になっているか、JavaScript に対応していません。<br>適切にこのページ表示する場合は JavaScriptを有効にするか、JavaScript
    に対応しているブラウザーでアクセスしてください。
</p> </noscript> <a href="#main" class="txtHidden skipLink">本文へ移動</a> <!-- GTAG --> <header class="l_header"> <div class="contentInner"> <div class="header-inner"> <!-- サイトロゴ --> <h1 class="header-logo"> <a href="/" class="logo-link"> <span class="logo-text">Astroサンプルサイト</span> </a> </h1> <!-- グローバルナビゲーション --> <nav class="c_nav"> <!-- スクリーンリーダー用見出し --> <h2 class="txtHidden">メニュー</h2> <!-- ハンバーガーボタン --> <button type="button" class="c_nav_btn" aria-expanded="false" aria-controls="nav-menu" aria-label="メニューを開く"> <span class="c_nav_btn_line"></span> <span class="c_nav_btn_label">MENU</span> </button> <!-- ラッパー --> <div class="c_nav_wrapper" id="nav-menu"> <!-- ドロワーパネル --> <div class="c_nav_inner"> <!-- メニュー本体 --> <ul class="c_nav_menu"> <li class="c_nav_item"> <a href="/" target="_self" class=" -active" data-tab>ホーム</a>  </li><li class="c_nav_item"> <a href="/about/" target="_self" class data-tab>概要</a>  </li><li class="c_nav_item -hasChild"> <a href="/sample/" target="_self" class data-tab>サンプル</a>  <button type="button" class="c_nav_trigger" aria-expanded="false"> <span class="visually-hidden"> サンプルのサブメニューを開く
</span> </button> <ul class="c_nav_child" hidden> <li> <a href="/sample/#hero" target="_self">ヒーロー</a> </li><li> <a href="/sample/#articles" target="_self">記事一覧</a> </li><li> <a href="/sample/#categories" target="_self">カテゴリー</a> </li><li> <a href="/sample/#qa" target="_self">Q&A</a> </li><li> <a href="/sample/#videos" target="_self">動画</a> </li> </ul>  </li> </ul> <!-- SP専用エリア --> <div class="c_nav_extra">  </div> </div> <!-- 閉じるボタン --> <button type="button" class="c_nav_close"> <span class="txtHidden">メニューを閉じる</span> </button> </div> </nav> </div> </div> </header>
